name: Python Security Scan

on:
  push:
    branches: [ main ]

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r .